### ISSUE TITLE
Design requirements

### ISSUE THREAD

**Issue by 0181532686cf4a31163be0bf3e6bb6732bf** [ErintLabs/ErintLabs.github.io#2]
Need to alter colors, add logo, favicon, change fonts and (possibly) add background files/images for slides

**Comment by landswellsong** [comment]
@lyssdod use checkbox notation:
- [x] alter colours
- [x] add favicon
- [x] add logo
- [x] change font
- [x] add background

**Comment by landswellsong** [comment]
@lyssdod close this maybe?

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
@landswellsong pictures and rest are ok?

**Comment by landswellsong** [comment]
@lyssdod no idea why you checked the background, unless you mean white is also background
